config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: %i[index show new create] do
    resources :reviews, only: %i[new create]
    member do
      get :review
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, presence: true, acceptance: { accept: %w[chinese italian japanese french belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: [0, 1, 2, 3, 4, 5], allow_nil: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    find_restaurant
  end

  def review
    find_restaurant
    @review = @restaurant.review
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%# Navbar starts%>
  <nav class="navbar navbar-expand-lg navbar-light bg-success">
  <div class="container-fluid">
    <a class="navbar-brand" href="/restaurants">Restaurants 🍽️</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/restaurants">List</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="/restaurants/new">Add a restaurant ➕</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
 <%# Navbar ends%>

    <%= yield %>
  </body>
</html>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/index.html.erb
 <div>
  <div class="mt-3">
    <ul style="list-style-type: none;">
      <% @restaurants.each do |restaurant| %>
      <div class="">
        <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
        <li><%= restaurant.category %></li>
      </div>
        <br>
      <% end %>
    </ul>
  </div>
 </div>

app/views/restaurants/new.html.erb
<div>
  <div class="mt-3 ml-4 mr-5"><h1>Add a restaurant ➕</h1>

    <%= simple_form_for [@restaurant] do |f| %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :phone_number %>
      <%= f.input :category%>
      <%= f.submit "Add restaurant", class: "btn btn-success rounded-pill" %>
    <% end %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div>
  <div class="mt-3 ml-4 mr-5">
    <h1><%= @restaurant.name%>📍</h1>
    <h6><%= @restaurant.address %></h6>
    <h6><%= @restaurant.phone_number %></h6>
    <h6><%= @restaurant.category %></h6>
  <br>
    <ul class="list-group">
      <% @restaurant.reviews.each do |review| %>
        <li class="list-group-item mb-2">
         <%= review.content %> <%= "⭐" * review.rating %></li>
      <% end %>
    </ul>
  <br>
  <%= link_to "Leave a review", new_restaurant_review_path(@restaurant), class: "btn btn-success rounded-pill" %>
  </div>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<div class="mt-3 ml-4 mr-5">
  <h1>Leave a review ⭐</h1>

    <%= simple_form_for [ @restaurant, @review ] do |f| %>
      <%= f.input :content %>
      <%= f.input :rating %>
      <%= f.submit "Submit review", class: "btn btn-success rounded-pill"%>
      <%= link_to "Back", restaurants_path, class: "btn btn-secondary rounded-pill" %>
    <% end %>

  <br>
  <br>
  <br>
  <br>
   <ul class="list-group">
    <% @restaurant.reviews.each do |review| %>
      <li class="list-group-item mb-2">
      <%= review.content %> <%= "⭐" * review.rating %></li>
    <% end %>
  </ul>
  <br>
</div>